version: '3.7'

services:
    backend:
        build: ./backend
        expose:
            - 3000
        environment:
            - DATABASE=hash
            - DB_USER=hash
            - DB_PASSWD=123456
            - DB_HOST=db
            - DB_PORT=5432
            - PORT=3000
        depends_on:
            - db
        networks:
            - app_net
            - db_net
        restart: always

    db:
        expose:
            - 5432
        image: postgres:latest
        environment:
            - POSTGRES_DB=hash
            - POSTGRES_USER=hash
            - POSTGRES_PASSWORD=123456
        networks:
            - db_net
        restart: always

    nginx:
        image: nginx:latest
        ports:
            - "8674:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./frontend/dist:/usr/share/nginx/html
        depends_on:
            - backend
        networks:
            - app_net
        restart: always

networks:
    app_net:
        driver: bridge
    db_net:
        driver: bridge