export const asciiToAsciiNum = (word: string) =>
    word
        .replace(/ee/g, '_2')
        .replace(/oo/g, '_4')
        .replace(/sh/g, 'E')
        .replace(/a/g, '_0')
        .replace(/e/g, '_1')
        .replace(/i/g, '_3')
        .replace(/o/g, '_5')
        .replace(/u/g, '_6')
        .replace(/y/g, '_7')
        .replace(/b/g, '0')
        .replace(/p/g, '1')
        .replace(/m/g, '2')
        .replace(/f/g, '3')
        .replace(/d/g, '4')
        .replace(/t/g, '5')
        .replace(/n/g, '6')
        .replace(/l/g, '7')
        .replace(/z/g, '8')
        .replace(/c/g, '9')
        .replace(/s/g, 'A')
        .replace(/g/g, 'B')
        .replace(/k/g, 'C')
        .replace(/h/g, 'D')
        .replace(/r/g, 'F');
