export const asciiToNum = (word: string) =>
    word
        .replace(/ee/g, '2̅')
        .replace(/oo/g, '4̅')
        .replace(/sh/g, 'E')
        .replace(/a/g, '0̅')
        .replace(/e/g, '1̅')
        .replace(/i/g, '3̅')
        .replace(/o/g, '5̅')
        .replace(/u/g, '6̅')
        .replace(/y/g, '7̅')
        .replace(/b/g, '0')
        .replace(/p/g, '1')
        .replace(/m/g, '2')
        .replace(/f/g, '3')
        .replace(/d/g, '4')
        .replace(/t/g, '5')
        .replace(/n/g, '6')
        .replace(/l/g, '7')
        .replace(/z/g, '8')
        .replace(/c/g, '9')
        .replace(/s/g, 'A')
        .replace(/g/g, 'B')
        .replace(/k/g, 'C')
        .replace(/h/g, 'D')
        .replace(/r/g, 'F');
